version: '3.7'

services:
    hiki:
        platform: linux/x86_64
        image: hiki-site-hiki
        #build:
        #    context: ./
        #    dockerfile: ./Dockerfile
        
        tty: true
        container_name: hiki
        volumes:
            - ./ruby:/app
            - ./ruby/hiki/DaiwaHouse/tdiary:/var/www/html/tdiary
        ports: 
            - "8080:80"
        restart: always
volumes:
    ruby: