version: '3.7'

services:
    ruby:
        platform: linux/x86_64
        build:
            context: ./
            dockerfile: ./Dockerfile
        tty: true
        container_name: ruby
        volumes:
            - ./ruby:/app
        ports: 
            - "8080:80"
        restart: always
volumes:
    ruby: