version: '3.7'

services:
    ruby:
        platform: linux/x86_64
        #image: ruby-test-ruby
        build:
           context: ./
           dockerfile: ./Dockerfile
        
        tty: true
        volumes:
            - ./ruby:/var/www/html
            - ./apache/log:/var/log/apache2
        ports: 
            - "8080:80"
        restart: always
volumes:
    ruby: